[project]
name = "pdf-search-engine"
version = "1.0.0"
description = "A production-ready hybrid search engine for PDF documents"
readme = "README.md"
requires-python = "==3.12.0"
dependencies = [
    "torch>=2.7.0",
    "torchvision>=0.22.0",
    "aiofiles>=24.1.0",
    "chromadb>=0.6.3",
    "fastapi>=0.115.12",
    "loguru>=0.7.3",
    "nltk>=3.9.1",
    "pydantic>=2.11.5",
    "pypdf>=5.6.0",
    "rank-bm25>=0.2.2",
    "sentence-transformers>=4.1.0",
    "streamlit>=1.45.1",
    "uvicorn[standard]>=0.34.3",
    "reportlab>=4.4.1",
    "pytest>=8.4.0",
]
authors = [
    {name = "PDF Search Engine Team"}
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu" },
]
torchvision = [
    { index = "pytorch-cpu" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src", "config.py", "main.py"]
